server:
  port: 3344

spring:
  application:
    name:  microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/CordellWL/springcloud-config.git #GitHub上面的git仓库名字
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
